### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by tormento** [kekyo/fdk-aac-win32-builder#9] opened 2021-05-31 07:49 UTC
I have tried to compile the new kit but all I get is broken builds with segmentation faults when trying test.sh.

The following errors have risen when compiling under msys2 x64:

In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
make[1]: Leaving directory '/f/Download/fdk-aac-win32-builder-master/stage/x86_64-w64-mingw32/fdkaac-1.0.2'
+ make install
make[1]: Entering directory '/f/Download/fdk-aac-win32-builder-master/stage/x86_64-w64-mingw32/fdkaac-1.0.2'
 /usr/bin/mkdir -p '/mingw64/x86_64-w64-mingw32/bin'
  /usr/bin/install -c fdkaac.exe '/mingw64/x86_64-w64-mingw32/bin'
 /usr/bin/mkdir -p '/mingw64/x86_64-w64-mingw32/share/man/man1'
 /usr/bin/install -c -m 644 man/fdkaac.1 '/mingw64/x86_64-w64-mingw32/share/man/man1'
make[1]: Leaving directory '/f/Download/fdk-aac-win32-builder-master/stage/x86_64-w64-mingw32/fdkaac-1.0.2'

Any idea?

**Comment by kekyo** [comment] 2021-05-31 10:46
Hmm, it's strange... My environment didn't cause it (i9-9980XE, MSYS x64)

* Could you test with CFLAGS downgraded options?
  For example: -O2 or  -O1 or -O0
* And try to update gcc newest packages by pacman.
* Another option (feel not related): Latest version contains automatic parallel build option named 'NPB' symbol inside build.sh. So force single build by `NPB=1` expression instead.

**Comment by nkh0472** [comment] 2021-05-31 13:44
Please paste the full terminal output for debugging. (At least make sure that the log content covers before&during the error occurs.)
Your log should look like this:
```
 MINGW64 ~/fdk-aac-win32-builder
$ ./build.sh
+ CFLAGS='-O3 -flto -march=native'
++ cat /proc/cpuinfo
++ grep processor
++ wc -l
+ NPB=4
+ '[' -z x86_64-w64-mingw32 ']'
+ cd stage
+ rm -rf x86_64-w64-mingw32
+ mkdir x86_64-w64-mingw32
+ cd x86_64-w64-mingw32
+ tar -zxf ../../artifacts/fdk-aac-0.1.6.tar.gz
+ tar -zxf ../../artifacts/fdk-aac-2.0.2.tar.gz
+ tar -zxf ../../artifacts/fdkaac-1.0.2.tar.gz
+ cd fdk-aac-0.1.6
+ CC='gcc -pipe -static-libgcc'
+ CXX='g++ -pipe -static-libgcc'
+ ./configure --prefix=/mingw64/x86_64-w64-mingw32/ 'CFLAGS=-O3 -flto -march=native'
……
```


---
My suggestion is 
1. Delete project folder and re-execute
```git clone https://github.com/kekyo/fdk-aac-win32-builder.git```
 to ensure that the local script content is up-to-date;
2. Update dependency package, you can refer to the following commands:
```
pacman -S mingw-w64-x86_64-gcc autoconf automake-wrapper make libtool
pacman -Syu
```

Follow-up recommendations need to be decided based on the attached log.

**Comment by tormento** [comment] 2021-06-02 12:19
Ok, I have reinstalled MSYS2 and followed the requirements.

The x64 build seems to be working despite some warnings [https://pastebin.com/JX2z4eU7](url)

The x86 one has problems with test.sh [https://pastebin.com/AkCgEaCg](url)

**Comment by nkh0472** [comment] 2021-06-02 15:19
I see, there is an same warning when compiling fdkaac 1.0.2 in your logs both with mingw32 and mingw64.

> src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
> src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here

<details>
<summary>same logs as you pasted 2 days ago </summary>
```
gcc -pipe -static-libgcc  -O3 -flto -march=native   -o fdkaac.exe src/aacenc.o src/caf_reader.o src/extrapolater.o src/limiter.o src/lpc.o src/m4af.o src/main.o src/metadata.o src/parson.o src/pcm_float_converter.o src/pcm_native_converter.o src/pcm_readhelper.o src/pcm_sint16_converter.o src/progress.o src/wav_reader.o  src/compat_win32.o fdkaac.o  -liconv -lfdk-aac -lm -lfdk-aac
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
In function 'apple_chan_chunk',
    inlined from 'caf_parse' at src/caf_reader.c:190:17,
    inlined from 'caf_open' at src/caf_reader.c:230:9,
    inlined from 'open_input' at src/main.c:754:27,
    inlined from 'main' at src/main.c:802:19:
src/pcm_readhelper.c:231:24: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  231 |             mapping[i] = i;
      |                        ^
src/main.c: In function 'main':
src/caf_reader.c:29:13: note: at offset 0 to object 'chanmap' with size 8 declared here
   29 |     uint8_t chanmap[8];
      |             ^
```
</details>
I think this is an upstream code error and has little relationship with this project. So you could [open an issue](https://github.com/nu774/fdkaac/issues/new/) with the author.

---
Besides, there are 2 parts of difference between those two logs when running build.sh (ignore x86_64/i686/64/32):

1. The change of compilation order is due to the parallel compilation `-j8` enabled. The difference here will not cause the compilation result to change. 
<details>
<summary>part of your logs</summary>
```
diff -r X:\fdk-aac-win32-builder x64.txt X:\fdk-aac-win32-builder x86.txt
……
133d183  
<   CXX      libAACdec/src/aacdec_hcr_bit.lo  
134a185  
>   CXX      libAACdec/src/aacdec_hcr_bit.lo  
```
</details>

2. The running time of the test program is affected by many factors, and the difference here can be ignored. But the running results of the two tests are different, which is very interesting. I guess the reason is related to the internal mechanism of fdk-aac or some automatically vectorize things in gcc. 
<details>
<summary>part of your logs</summary>
```
802,817c853,871  
< [100%] 01:35.852/01:35.852 (77x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.239  
< [100%] 01:35.852/01:35.852 (63x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.521  
< [100%] 01:35.852/01:35.852 (61x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.568  
< [100%] 01:35.852/01:35.852 (97x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:00.989  
< [100%] 01:35.852/01:35.852 (63x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.521  
< [100%] 01:35.852/01:35.852 (72x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.333  
< [100%] 01:35.852/01:35.852 (90x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.067  
< [100%] 01:35.852/01:35.852 (72x), ETA 00:00.000  
< 4227066/4227066 samples processed in 00:01.333  
---  
> [100%] 01:35.852/01:35.852 (73x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.317  
> [100%] 01:35.852/01:35.852 (55x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.757  
> [100%] 01:35.852/01:35.852 (57x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.679  
> [100%] 01:35.852/01:35.852 (86x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.114  
> [100%] 01:35.852/01:35.852 (57x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.679  
> [100%] 01:35.852/01:35.852 (69x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.397  
> [100%] 01:35.852/01:35.852 (79x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.207  
> [100%] 01:35.852/01:35.852 (66x), ETA 00:00.000  
> 4227066/4227066 samples processed in 00:01.443  
> references/BattleThemeA_p29_44_128.pcm artifacts/i686-w64-mingw32_test/BattleThemeA_p29_44_128.pcm differ: char 142007, line 728  
> references/BattleThemeA_p2_44_256.pcm artifacts/i686-w64-mingw32_test/BattleThemeA_p2_44_256.pcm differ: char 389255, line 2998  
> references/BattleThemeA_p2_44_m5.pcm artifacts/i686-w64-mingw32_test/BattleThemeA_p2_44_m5.pcm differ: char 12161029, line 102943  
```
</details>

---
Not long ago, I confirmed (see #5 ) that the encoding results of different versions of fdk-aac are different, but all the output files are playable, and the bitrate also meets the requirements of parameters. Although I didn't verify the coding difference between x86 and x64 at that time, I can still boldly guess that their output is normal. If you need to further confirm the correctness of the encoding, please proceed to the following 3 steps:

1. execute commands below to verify if `Stream #0:0(und)` field matches the `encoder` field:
```
test-materials/ffmpeg.exe -i artifacts/i686-w64-mingw32_test/BattleThemeA_p2_44_128.aac
test-materials/ffmpeg.exe -i artifacts/i686-w64-mingw32_test/BattleThemeA_p2_44_256.aac
test-materials/ffmpeg.exe -i artifacts/i686-w64-mingw32_test/BattleThemeA_p2_44_m5.aac
```

2. Use your own audio player to test above 3 aac files are playable.

3. (Optional, but authoritative) Use [The Codec Test Service](https://test.xhe-aac.com/) provided by Fraunhofer IIS to verify encoder followed by their guide.

**Comment by nkh0472** [comment] 2021-06-03 03:04
Forget about it, I admit that I am a programming idiot... Let someone else do the fix.
At present, this is just a warning, not an error, and it might not have much impact...

I'll open an issue in that repo.

**Comment by kekyo** [comment] 2021-06-03 10:55
I think I will retention this issue as is when that will be fixed.

**Comment by tormento** [comment] 2021-06-07 05:54
In today MSYS2 release:

Changes:

New clang64 environment

Is the ,/build.sh compatible? I'd like to give it a try and see if it can compile without warnings.

**Comment by nkh0472** [comment] 2021-06-07 07:23
> In today MSYS2 release:
> 
> Changes:
> 
> New clang64 environment
> 
> Is the ,/build.sh compatible? I'd like to give it a try and see if it can compile without warnings.

There is no change in the terminal output.

**Comment by nkh0472** [comment] 2021-06-07 08:20
I open PR #10 to temporarily disable this (maybe harmless) warning.

Now the compilation process does not generate any warnings above.

Now there is no problem with the running of the compiled script, and the info about warnings is reported to upstream, so you can close this issue.

For any concern about the warnings, please discuss in https://github.com/nu774/fdkaac/issues/46

**Comment by kekyo** [comment] 2021-06-08 02:45
PR #10 was merged into master.
Could you test it @tormento ?

**Comment by tormento** [comment] 2021-06-08 08:36
@kekyo I have tried the new merged master and I think it works ok, apart from the differences in x86 test encodings.

[x64 output](https://pastebin.com/QQeGXbFU)
[x86 output](https://pastebin.com/tKZGinRd)

The only issue, not knowing if a but or a feature, is that the exe needs the libraries to work. Is it possible to have a standalone version too?

**Comment by nkh0472** [comment] 2021-06-08 08:56
> The only issue, not knowing if a bug or a feature, is that the exe needs the libraries to work. Is it possible to have a standalone version too?

That is called shared and static build.
This two software usually not be updated at the same time.
So using a shared build can make you only replace the updated files without recompiling them all.

If you want, you can set it to static build through changing `CFLAGS` when compiling fdkaac.
I have randomly searched this [webpage](https://stackoverflow.com/questions/725472/static-link-of-shared-library-function-in-gcc), which can help you get started on how to achieve this.
But remember that the `makefile` of current shared build  is made by the original project author. 
So we can't guarantee that your changes won't cause unknown problems (Although it usually doesn't happen).

**Comment by tormento** [comment] 2021-06-08 08:59
@nkh0472 that goes beyond my capabilities :) That's why I am using a semi-automated build tool.

**Comment by kekyo** [comment] 2021-06-09 23:56
PR #16 was merged. We drop an option `-flto`, the option mades global-wide inlining (and another) optimization but currently doesn't test on original fdkaac distribution devs.

Do you have related any other problem? Would you close if nope.

**Closed** 2022-11-21 00:09 UTC
